services:
  n8n:
    image: n8nio/n8n

    ports:
      - "5678:5678"

    environment:
      - TZ=${TZ}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}

    volumes:
      - /tmp/.n8n:/home/node/.n8n